name = "intent-map"
compatibility_date = "2025-06-15"

# Specify the directory containing static files for Pages
pages_build_output_dir = "."

# Environment variables (if needed)
[vars]
# Add any environment variables here 